version: 0.2

env:
  variables:
    HOME_DIR: "/home/ec2-user"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - yum install -y python-devel
  build:
    commands:
      - echo Build starting on `date`
      - docker build -t app-backend:$COMMIT_ID -f backend/Dockerfile
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    backend:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - backend/**/*
    frontend:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - frontend/**/*